### ISSUE TITLE
throttle nats output

### ISSUE THREAD

**Issue by pretentious7** [drifting-in-space/plane#120]
In certain conditions (ie. when a nonexistent backend is getting polled very frequently), too many messages are logged to nats. Having a throttle would alleviate this issue.

**Comment by paulgb** [comment]
If you're thinking of implementing this, let's talk first, there's probably built-in NATS functionality (either in the client or server) that we can take advantage of.

**Comment by pretentious7** [comment]
I don't remember why this was a thing, but nats is pretty quiet now so can close i think
