### ISSUE TITLE
add regression tests for spawn times across different spawner versions with some example containers.

### ISSUE THREAD

**Issue by pretentious7** [drifting-in-space/plane#131]

**Comment by paulgb** [comment]
Can you elaborate on what this would look like? My hunch is that the variability of startup time for a regular container would be variable/noisy enough to mask any variability in the (relatively low-overhead) spawner-side of spawning.

**Comment by pretentious7** [comment]
you're right, I think a measurement for scheduleRequest -> Spawn would be good though.

**Comment by paulgb** [comment]
This would make sense when we are doing more sophisticated scheduling, but for now I don't think it would tell us much.

**Comment by paulgb** [comment]
I think the things that we're most interested in here live outside of Plane, and are deployment-specific. It's worth investigating doing these tests on staging, but I'm going to close this issue, feel free to re-open it on linear.
