### ISSUE TITLE
Consolidate `backend_to` maps into one map.

### ISSUE THREAD

**Issue by pretentious7** [drifting-in-space/plane#180]
This will be useful to ensure we don't leak resources after a container is swept.

**Comment by paulgb** [comment]
Rust lifetimes themselves don't change program behaviour, they only place limits on the behaviour that is allowed, so a good way of approaching problems like this is to ask “what behaviour would ensure that all container resources are cleaned up when a container is swept”.

A nice way to do this is to create a `struct` which takes ownership of all container-bound threads/resources, and cleans them up in its drop handler (either explicitly, if we implement `drop`, or implicitly, if we rely on `drop` automatically being called on each member).

This way we would replace all of the `backend_to` [maps](https://github.com/drifting-in-space/spawner/blob/df570118e1d06f6b54a61e7dd8537184ad31d654/drone/src/agent/executor.rs#L46-L50) with a map from backend ID to the new struct.

Note that the drop handler of a [`JoinHandle`](https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html) does **not** automatically abort the task, but it's easy to write a wrapper around a `JoinHandle` that would do so.

Some open design questions:
- Should we also combine all container-bound event loops (stats, logs) into one event loop with a select? I'm not persuaded that the result is cleaner, but it's something to consider.
- Should we consolidate the code for (re)connecting to a container into this new `struct`? That way, both initial container creation as well as resuming a connection to an existing container after a restart could use the same code, e.g. `BackendMonitor::for_container(&container_name)`.

**Comment by paulgb** [comment]
I've updated the title to reflect the more specific change that is needed here.

**Comment by paulgb** [comment]
This is now implemented in #186
