### ISSUE TITLE
Containers get stuck in Loading state in case of OCI runtime create failure

### ISSUE THREAD

**Issue by pretentious7** [drifting-in-space/plane#193]
to repro:
clone https://github.com/drifting-in-space/jamsocket-jupyter-notebook.git

`chmod -x run.sh`

`docker build -t jupyter-notebook .`

then on `docker run -p 8080:8080 --env PORT=8080 -it jupyter-notebook`

you should see:

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "../run.sh": permission denied: unknown.
`

and with local spawner, in cli directory run `cargo run spawn jupyter-notebook`, and see that the last status on nats is Loading,  it should be ErrorLoading.

**Comment by paulgb** [comment]
Good catch. I wonder if it’s worth exposing the fact that a container failed to create vs. failed to load?

Maybe we treat both as as ErrorLoading, but then pass along the error string and which stage the error occurred at.
