### ISSUE TITLE
plane-cli list-dns error

### ISSUE THREAD

**Issue by MyCADDev** [drifting-in-space/plane#258]
I followed along the example and opened the drop four app in firefox

plane-cli list-dns is giving this below error

```
2022-11-17T23:16:57.797046Z  INFO async_nats::options: event: connected
Error: NATS Error: Custom { kind: Other, error: "error while processing messages from the stream: 404, Some(\"No Messages\")" }
```

**Comment by MyCADDev** [comment]
@paulgb - I'm getting the same error. I did a pull of your changes and rebuilt the containers. Am I missing anything?

**Comment by paulgb** [comment]
The change also impacts the cli, so it might be that you need to re-build or re-install that too. The getting started guide mentions [two ways](https://plane.dev/docs/getting-started#using-the-cli) to use the cli, so here are the instructions for both ways.

If you installed the cli from `cargo`, it will be:

```
# in plane repo directory
git pull
cargo install --path=cli
```

If you aliased the Plane CLI to Docker, it will be:

```
docker pull ghcr.io/drifting-in-space/plane-cli
```

**Comment by MyCADDev** [comment]
This works now - thanks @paulgb

**Comment by paulgb** [comment]
Great, thanks for confirming!
