### ISSUE TITLE
Refactor how drone state propagates to controller and other consumers

### ISSUE THREAD

**Issue by paulgb** [drifting-in-space/plane#278]
Our current approach to state is to use non-Jetstream NATS and treat it as unreliable and ephemeral. Drones simply rebroadcast all of their current state frequently to keep that state alive in the system. Consumers of that state will cache it for a limited TTL, and then intentionally forget it if it is not rebroadcast again.

This has some maintenance benefits, because even though the system is stateful, it does not have long-persisted state. It does have a few downsides, though:

- As the system state grows, it can become very chatty to have all state rebroadcast frequently. This is especially relevant as we add more state to be used for scheduling.
- There's no system-level consensus on when a drone has become lost, or who is responsible for declaring it lost. As a result, we currently do not handle drone loss.
- A bunch of code that doesn't really have to do with events (i.e. just needs a static view of cluster state) has to deal with the event-based nature of the data.

Now that we have a better understanding of the semantics of Jetstream (including @pretentious7's deep dives), I propose returning to using Jetstream to store Plane's runtime state.

The approach I propose is:
- All state used for scheduling and routing is moved into a single Jetstream stream.
- The stream captures all subjects that match `cluster.*.drone.*.sm.>` and stores the last message on each subject.
- One-time consumers of this state read a “snapshot” copy by reading the last message on every subject from NATS. Once the snapshot is read, the stream consumer is dropped.
- Long-term consumers of this state (including the DNS server and scheduler) keep a single local copy of a view into all system state. The process has a single global instance of a `SystemViewReplica` which owns a NATS subscription which processes change events from the drones. These events are applied to the shared data structure. Consumers do not need to be aware of the event-based nature of the data, they just access system state by calling methods of a data structure. All requests are synchronous, since a replica of the entire system state data structure is stored locally.

Tasks:
- [x] Use this model for the CLI client, and broadcasts the appropriate messages. The old messages remain for now. #274
- [ ] Switch to the new model for DNS serving. #285 
- [ ] Switch to the new model for scheduling.
- [ ] Remove `BackendStateMessage` and `SetDnsRecord` (we will keep `SetAcmeDnsRecord` for ACME, counter to the previous plans to do all DNS through `SetDnsRecord`).
- [ ] Handle lost drones appropriately and send update messages on all of their backends.

Consumers of `BackendStateMessage` will need to change, but it's mostly just a matter of listening on a different subject wildcard as the message has mostly the same information.

This will fix #265, and supersede #145’s proposed changes to `SetDnsRecord` and `BackendStateMessage`.

**Comment by pretentious7** [comment]
so `SetDnsRecord` isn't needed anymore because the DNS server process knows where the backends are through its `SystemViewReplica`, correct?

**Comment by paulgb** [comment]
Yes, by the time `SetDnsRecord` is removed, this will be true. It will take a few PRs to get there so that we can do staged deploys.
