### ISSUE TITLE
Allow accessing other ports

### ISSUE THREAD

**Issue by paulgb** [drifting-in-space/plane#293]
`SpawnRequest` could include an optional allowlist of ports. When a port is on the allowlist, accessing `p-{port}.{backend}.{cluster}` would proxy the request to that port instead of 8080.

This involves:

- [ ] Modify the DNS server so that `*.{backend}.{cluster}` resolves to the same IP as `{backend}.{cluster}`.
- [ ] Modify the `SpawnRequest` schema to pass through an optional allowlist of ports.
- [ ] Have the drone insert a record into the proxy table for each allowlisted port.

Services would still be HTTPS, and proxying would be layer 7, this would just allow the container to listen on multiple ports. Non-HTTPS protocols and UDP are out of scope for this issue.

**Comment by paulgb** [comment]
Brought up offline by @ajbouh and @mycaddev, feel free to suggest changes to the approach.

**Comment by MyCADDev** [comment]
Thanks @paulgb !!

**Comment by paulgb** [comment]
Sorry, this should have been closed as not planned rather than completed. We are focusing on making Plane as reliable as possible with the current API surface before extending it further.
