### ISSUE TITLE
Check container cleanup logic

### ISSUE THREAD

**Issue by paulgb** [drifting-in-space/plane#301]
As reported in #300

**Comment by t-moe** [comment]
Its possible that this only occurs if I restart plane (docker compose down) while containers are running. If I'm correct, by looking at the logs, plane picks up the still running (deployed) containers after restart. But let's check if they're also swept/removed properly in that case.

**Comment by paulgb** [comment]
Thanks, that's helpful and it's possible that there is an edge case there that we haven't encountered in production because of our habit of rotating drones.

It is something that we should support, and we actually have [a test](https://github.com/drifting-in-space/plane/blob/fd07f14c4ea0fb6e75102649b6242044c9ee5295/dev/tests/agent.rs#L653) for it, but it's very possible that that test is not comprehensive.
