### ISSUE TITLE
A container that fails to start (ie invalid executable in RUN command), gets stuck in BackendState::Loading forever

### ISSUE THREAD

**Issue by pretentious7** [drifting-in-space/plane#343]
Should probably transition to BackendState::ErrorLoading.

**Comment by paulgb** [comment]
Agreed that this is a bug. Thoughts on making it ErrorLoading vs. ErrorStarting vs. a new type of error?

**Comment by pretentious7** [comment]
This doesn't happen, I had an incorrect thing running where the executor was being dropped, my bad.

Correctly returns ErrorLoading.
