### ISSUE TITLE
[Bug] environment variable `PORT` not set automatically by plane

### ISSUE THREAD

**Issue by HunterLarco** [drifting-in-space/plane#445]
In the [jamsocket docs](https://docs.jamsocket.com/api-docs/#backend-containers) it describes

> All backends will have the following reserved env vars passed to them. Env vars with these names passed by the user when spawning will be overridden by the platform-provided values.
> 
> * PORT
> * JAMSOCKET_NAME
> * JAMSOCKET_URL
> * JAMSOCKET_SERVICE

My team is using plane.dev to emulate jamsocket locally and expected this behavior at least for `PORT` to be identical but it is not. Plane's controller/drone do not automatically apply the env variable PORT to containers.

To have more parity between Jamsocket and local plane.dev deployments for BYOC customers this would be nice to address.

Currently we have modified our internal jamsocket HTTP client to detect when we're running locally and to automatically add `env: { PORT: request.port ?? '8080' }` to our spawn requests but this is a little brittle since it may diverge from jamsocket/plane's behavior.

**Comment by paulgb** [comment]
Good catch. I've created a PR to fix the `PORT` one for now since it's low-hanging fruit. Are the other ones important to you now, or just desired for parity?

**Comment by HunterLarco** [comment]
Thanks! The rest i don't think are very important mostly because they're prefixed with JAMSOCKET_ making them clearly not a feature which should not be expected to have parity with plane. But the PORT was different because (a) it's not prefixed and (b) it's an incredibly commonly used environment variable
