### ISSUE TITLE
Can we add a version that uses MySQL

### ISSUE THREAD

**Issue by shijunti19** [drifting-in-space/plane#656]
Can we add a version that uses MySQL

Small websites are generally developed using MySQL, which is more conducive to popularization

**Comment by paulgb** [comment]
Hi @shijunti19, unfortunately some Postgres-specific features (like [NOTIFY](https://www.postgresql.org/docs/current/sql-notify.html)) are crucial to Plane’s operation.

If your site is sufficiently small that you only need one drone/proxy/controller, you might consider our [quickstart](https://hub.docker.com/r/plane/quickstart) image which bundles all three of those as well as a Postgres server into one container. It's generally not recommended for production, but it should be fine at a small scale. We don't have docs on it yet but if you'd like to try that path I can write something up.
